### ISSUE TITLE
很喜欢这个小巧的页面

### ISSUE THREAD

**Issue by NanJishen** [channg/your-navigation#1]
很喜欢这个小巧的页面，请问能否增加个导出：localStorage 里的数据呈现到页面上就行，比如点击个按钮，将localStorage数据显示到页面下方，这样可以复制保存。

**Comment by channg** [comment]
https://chrome.google.com/webstore/detail/new-tab-navigation/dahpcbimcligpmaffmaihcplfcejmgoi/related?hl=zh-CN&authuser=0

使用这个插件可以跨端同步

**Comment by NanJishen** [comment]
> https://chrome.google.com/webstore/detail/new-tab-navigation/dahpcbimcligpmaffmaihcplfcejmgoi/related?hl=zh-CN&authuser=0
> 
> 使用这个插件可以跨端同步

收到，这个插件的话就是永久同步到云端了吧？我主要怕丢失

**Comment by channg** [comment]
@NanJishen 是的  将书签报错了chrome的配置中，换浏览器也都直接同步的
